admin:
  emails:
  - admin@example.com
  
csrf:
  ssl_strict: false
  time_limit: 3600
database:
  track_modifications: False
  uri: platform.db
session:
  cookie:
    httponly: true
    samesite: Lax
    secure: false
  lifetime_days: 7

logging:
  level: INFO

# 游戏平台配置
games:
  default_type: "avalon"     # 默认游戏类型
  default_type_name: "阿瓦隆" # 默认游戏类型显示名称
  types:
    - id: avalon
      name: 阿瓦隆
      players: 7   # 默认游戏需要7名玩家
  matchmaking:
    timeout: 60  # 匹配超时时间（秒）
    interval: 5  # 匹配检查间隔（秒）

# AI代码配置
ai:
  max_file_size: 524288  # 最大文件大小 (512 KB)
  execution_timeout: 1000  # AI代码执行超时时间(毫秒)
  memory_limit: 104857600  # 内存限制 (100 MB)
  sandbox_enabled: true  # 是否启用沙箱执行
