csrf:
  ssl_strict: false
  time_limit: 3600

database:
  track_modifications: False
  uri: platform.db

session:
  cookie:
    httponly: true
    samesite: Lax
    secure: false
  lifetime_days: 7

logging:
  level: INFO

# AI 代码上传目录
AI_CODE_UPLOAD_FOLDER: uploads/




# 初始用户配置
INITIAL_USERS:
  # Smart AI 用户系列
  - username: smart_user1
    email: smart1@example.com
    password: password123
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user2
    email: smart2@example.com
    password: password123
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user3
    email: smart3@example.com
    password: password123
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user4
    email: smart4@example.com
    password: password123
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user5
    email: smart5@example.com
    password: password123
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
  - username: smart_user6
    email: smart6@example.com
    password: password123
    ai_code:
      name: Smart AI
      description: DeepSeek增强型AI玩家
      file_path: game/smart_player.py
      make_active: true
      
  # Basic AI 用户系列
  - username: basic_user1
    email: basic1@example.com
    password: password123
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user2
    email: basic2@example.com
    password: password123
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user3
    email: basic3@example.com
    password: password123
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user4
    email: basic4@example.com
    password: password123
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user5
    email: basic5@example.com
    password: password123
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true
  - username: basic_user6
    email: basic6@example.com
    password: password123
    ai_code:
      name: Baseline AI
      description: 基础AI玩家
      file_path: game/basic_player.py
      make_active: true


DATA_DIR: ./data

# 示例回放设置
EXAMPLE_REPLAY:
  file_path: "./example/example_game_replay.json"  # 修改为正确的相对路径
  # 添加这一行，提供有效ID避免系统查询不存在的battle_id
  battle_id: "example"  